# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: AWS_WebApp_Project_Terraform
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  AWS_WebApp_Project_Terraform:
    runs-on: ubuntu-latest
    steps:
    # Clones repo 
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::536984667329:role/Access_TF_resources_arch1
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform 
        run: terraform fmt -check

      - name: Terraform init
       # working-directory: AWS_WebApp_Project_Terraform
        run: terraform init

      - name: Terraform validate
       # working-directory: AWS_WebApp_Project_Terraform
        run: terraform validate

      - name: Terraform plan
       # working-directory: AWS_WebApp_Project_Terraform
        run: terraform plan

          
